---
name: HTTP-DAV-Browse
version: 0.02
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
abstract: browse the WebDAV tree
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTTP::DAV: 0.38
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::StrictConstructor: 0
  URI: 0
build_requires:
  LWP::UserAgent: 0
  Test::Exception: 0
  Test::More: 0
provides:
  HTTP::DAV::Browse:
    file: lib/HTTP/DAV/Browse.pm
    version: 0.02
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
